version: '3'
services:
  reclaim-api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=localpassword
      - DB_DATABASE=origin
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CONTRACT_ADDRESS=0x6767922A2048a09d1AA1E32f7b3C4f2dC512D3E1
      - CLAIM_PRIVATE_KEY=0xf6cc9407aa3d61e7b1fe2e62c2e984018168a1b0df9cb44482e3cfb568363373
      - ETH_ENDPOINT=https://kovan.infura.io/
    volumes:
      - "./dist:/server/dist"
      - "./migrations:/server/migrations"
    ports:
      - "3000:3000"
  postgres:
    image: postgres:9.6
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=reclaim
      - POSTGRES_PASSWORD=localpassword
  redis:
    image: redis:3.2.11
    ports:
      - "7379:6379"
